apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-demo

resources:
  - ../../base/namespace.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
